services:
  webservercnot:
    networks:
      - npm-cnotperso-webserver-net
      - internal-net

  dbservercnot:
    networks:
      - internal-net

  pmacnot:
    networks:
      - npm-cnotperso-pma-net
      - internal-net

networks:
  npm-cnotperso-webserver-net:
    external: true
  npm-cnotperso-pma-net:
    external: true
  internal-net:
