services:
  webserver:
    networks:
      - npm-cnot-webserver-net

  pma:
    networks:
      - npm-cnot-pma-net

networks:
  npm-cnot-webserver-net:
    external: true
  npm-cnot-pma-net:
    external: true