version: '3.8'
services:
  webservercnot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: dev
    restart: unless-stopped
    depends_on:
      dbservercnot:
        condition: service_healthy
    environment:
      MYSQL_HOST: dbservercnot
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JOURNAL_NAME: ${JOURNAL_NAME}
    ports:
      - "${HTTP_WEB_PORT}:80"
    volumes:
      - ./src:/var/www/html
      - "${ENTRIES_DATA_PATH}:/var/www/html/entries"
      - "${ATTACHMENTS_DATA_PATH}:/var/www/html/attachments"
    command: /bin/sh -c "chown -R www-data:www-data /var/www/html/entries && apache2-foreground"

  dbservercnot:
    image: mysql:9.3.0
    restart: unless-stopped
    volumes:
      - "${DB_DATA_PATH}:/var/lib/mysql"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      interval: 10s
      retries: 10
