services:  
  
  # WEB      
  webservercnotperso:       
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile to use
    restart: unless-stopped      
    depends_on:
      - dbservercnotperso
    environment:
      MYSQL_HOST: dbservercnotperso
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JOURNAL_NAME: ${JOURNAL_NAME}
      APP_PASSWORD: ${APP_PASSWORD}
    volumes:
      - "${ENTRIES_DATA_PATH}:/var/www/html/entries"
    command: /bin/sh -c "chown -R www-data:www-data /var/www/html/entries && apache2-foreground"

  # DATABASE
  dbservercnotperso:
    image: mysql
    restart: unless-stopped
    volumes:
      - "${DB_DATA_PATH}:/var/lib/mysql"
    environment:
      MYSQL_USER: ${MYSQL_USER}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - grafana-cnotpersomysql-net
      - prometheus-cnotpersomysql-net

  # PHPMYADMIN (PMA)
  pmacnotperso:
    image: phpmyadmin
    depends_on:
      - dbservercnotperso
    environment:
      PMA_HOST: dbservercnotperso
      UPLOAD_LIMIT: 250M
    restart: unless-stopped

networks:
  grafana-cnotpersomysql-net:
    external: true
  prometheus-cnotpersomysql-net:
    external: true
