services:
  webservercnotperso:
    networks:
      - npm-cnotperso-webserver-net
      - internal-net

  dbservercnotperso:
    networks:
      - internal-net

  pmacnotperso:
    networks:
      - npm-cnotperso-pma-net
      - internal-net

networks:
  npm-cnotperso-webserver-net:
    external: true
  npm-cnotperso-pma-net:
    external: true
  internal-net:
