services:  
  
  # WEB      
  webserver:       
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile to use
    restart: always      
    depends_on:
      - dbserver
    environment:
      MYSQL_HOST: dbserver
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JOURNAL_NAME: ${JOURNAL_NAME}
      APP_PASSWORD: ${APP_PASSWORD}
    volumes:
      - "${ENTRIES_DATA_PATH}:/var/www/html/entries"
    command: /bin/sh -c "chown -R www-data:www-data /var/www/html/entries && apache2-foreground"
#    networks:
#      - internal-net # Connection with other services in this stack 

  # DATABASE
  dbserver:
    image: mysql
    restart: always
    volumes:
      - "${DB_DATA_PATH}:/var/lib/mysql"
    environment:
      MYSQL_USER: ${MYSQL_USER}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${MYSQL_DATABASE}
#    networks:
#      - internal-net # Connection with other services in this stack 

  # PHPMYADMIN (PMA)
  pma:
    image: phpmyadmin
    depends_on:
      - dbserver
    environment:
      PMA_HOST: dbserver
      UPLOAD_LIMIT: 250M
    restart: always
#    networks:
#      - internal-net # Connection with other services in this stack 

#networks:
#  internal-net:  # Network specific to this stack
