services:
  webserver:
    networks:
      - npm-cnot-webserver-net
      - internal-net

  database:
    networks:
      - internal-net

  phpmyadmin:
    networks:
      - npm-cnot-pma-net
      - internal-net

networks:
  npm-cnot-webserver-net:
    external: true
  npm-cnot-pma-net:
    external: true
  internal-net:
    external: true
    name: cnot_internal-net
